name: common_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - numpy
    - pandas
    - matplotlib
    - pillow
    - seaborn
    - jupyter
    - sqlalchemy
    - lightning
    - loguru
    - hydra-core
    - pip:
        - opencv-python
        - requests
        - aiohttp
        - fastapi
        - uvicorn[standard]
        - pytest
        - llama-cpp-python
        - datasets
        - diffusers
        - transformers
        - sentence-transformers
        - evaluate
        - rouge_score
        - tensorboard
        - scikit-learn
        - accelerate
        - bitsandbytes
        - hf_xet
        - peft
        - tiktoken
        - langchain
        - langchain-community
        - langchain-ollama
        - langchain-nomic
        - langchain-chroma
        - nomic[local]
        - langgraph
        - langfuse
        - tavily-python
        - ollama
        - pypdf
