log_level: TRACE  # TRACE WARNING

task:
    debug_mode: True  # True False
    embedding_model: nomic-embed-text
    llm: 'gemma2:9b'  # 'gemma2:9b' phi3

    chunk_size: 256  # 1024 512 256
    n_vector_results: 16  # 8 16

    rewrite_user_prompt: False # True False
    rerank: True

paths:
    roots:
        ws: D:/code # /home/stud/ath/ath_ws/others  D:/code
        project: ${paths.roots.ws}/library_rag
        output: ${paths.roots.project}/output
        data: ${paths.roots.project}/data

    output:
        logs: ${paths.roots.output}/logs

    storage: ${paths.roots.project}/storage

llm:
    phi3:
        context_window_size: 8192
    'gemma2:9b':
        context_window_size: 8192
