log_level: TRACE  # TRACE WARNING

task:
    debug_mode: True  # True False
    embedding_model: nomic-embed-text
    llm: 'phi3.5'  # 'gemma2:9b' 'phi3.5'

    chunk_size: 1024  # 1024 512 256
    n_results: 8  # 8 16

    temperature: 0.1
    max_tokens: 200

    rewrite_user_prompt: False # True False
    rerank: True

    collection_name: books

paths:
    roots:
        ws: D:/code # /home/stud/ath/ath_ws/others  D:/code
        project: ${paths.roots.ws}/library_rag
        output: ${paths.roots.project}/output
        data: ${paths.roots.project}/data

    output:
        logs: ${paths.roots.output}/logs

    storage: ${paths.roots.project}/storage

llm:
    'phi3.5':
        context_window_size: 128000
    'gemma2:9b':
        context_window_size: 8192
